// Ingredient knowledge base, consumed by /ingredients/:id and the map's spot resolver.
export const ingredients = {
  'pecorino-romano': {
    id: 'pecorino-romano', name: 'Pecorino Romano DOP', region: 'lazio', regionName: 'Lazio',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'One of Italy\'s oldest cheeses, Pecorino Romano DOP is a hard, salty sheep\'s milk cheese produced in Lazio and Sardinia. Its sharp, pungent flavour makes it essential to Roman pasta dishes.',
    flavors: ['Salty', 'Sharp', 'Umami', 'Nutty', 'Pungent'],
    pairings: ['Black Pepper', 'Guanciale', 'Eggs', 'Pasta', 'Chianti', 'Honeys'],
    pairingIds: ['black-pepper', 'guanciale', 'eggs', 'pasta', 'chianti', 'honey'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Aged', 'Low Lactose'],
    producerIds: ['caseificio-salvo', 'formaggi-argiolas'],
    recipeIds: ['cacio-e-pepe', 'trofie-al-pesto'],
  },
  'parmigiano-reggiano': {
    id: 'parmigiano-reggiano', name: 'Parmigiano Reggiano DOP', region: 'emilia_romagna', regionName: 'Emilia-Romagna',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'The "King of Italian Cheeses" — an aged, granular hard cheese produced in Parma, Reggio Emilia, and surrounding provinces. Aged 12 to 36 months, its crystalline texture and complex umami depth are unparalleled.',
    flavors: ['Umami', 'Nutty', 'Savory', 'Sweet', 'Crystalline'],
    pairings: ['Prosciutto di Parma', 'Balsamic Vinegar', 'Pasta', 'Risotto', 'Lambrusco'],
    pairingIds: ['prosciutto-di-parma', 'balsamic-vinegar', 'pasta', 'risotto', 'lambrusco'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Aged', 'Lactose-Free'],
    producerIds: ['caseificio-gennari', 'caseificio-lombardo'],
    recipeIds: ['tagliatelle-ragu', 'risotto-milanese', 'tajarin-tartufo'],
  },
  'tartufo-bianco': {
    id: 'tartufo-bianco', name: "Tartufo Bianco d'Alba", region: 'piemonte', regionName: 'Piedmont',
    image: '/img/products/tartufo-morra.webp',
    description: "The white truffle from Alba is the most prized food in Italy — earthy, garlicky, honey-sweet, and intensely perfumed. Harvested October to December in the Langhe forests. Never cooked. Always shaved raw.",
    flavors: ['Earthy', 'Garlicky', 'Honey', 'Musky', 'Intense'],
    pairings: ['Tajarin', 'Butter', 'Parmigiano Reggiano', 'Risotto', 'Eggs'],
    pairingIds: ['tajarin', 'butter', 'parmigiano-reggiano', 'risotto', 'eggs'],
    nutrition: ['Low Calorie', 'High in Antioxidants', 'Seasonal', 'Rare'],
    producerIds: ['tartufi-morra', 'tartufi-ponti'],
    recipeIds: ['tajarin-tartufo'],
  },
  'pesto-genovese': {
    id: 'pesto-genovese', name: 'Pesto Genovese DOP', region: 'liguria', regionName: 'Liguria',
    image: '/img/products/pesto-rossi.webp',
    description: 'True Pesto Genovese is made only with DOP Genovese basil, Ligurian extra virgin olive oil, Sardinian Fiore Sardo, Parmigiano, pine nuts, and garlic. Never heat it. Always use a marble mortar ideally.',
    flavors: ['Fresh', 'Herbal', 'Nutty', 'Savory', 'Bright'],
    pairings: ['Trofie', 'Focaccia', 'Burrata', 'Cherry Tomatoes', 'Pecorino'],
    pairingIds: ['trofie', 'focaccia', 'burrata', 'cherry-tomatoes', 'pecorino-sardo'],
    nutrition: ['High in Healthy Fats', 'Antioxidant-rich', 'Vegetarian', 'Gluten-Free'],
    producerIds: ['pesto-rossi', 'frantoio-roi'],
    recipeIds: ['trofie-al-pesto'],
  },
  'san-marzano': {
    id: 'san-marzano', name: 'San Marzano DOP Tomatoes', region: 'campania', regionName: 'Campania',
    image: '/img/products/sanmarzano-gustarosso.webp',
    description: 'San Marzano tomatoes grown in the volcanic plains of Sarno — the gold standard for tomato sauce. Lower acidity, fewer seeds, and a meaty flesh that makes them the only tomato permitted in authentic Neapolitan pizza.',
    flavors: ['Sweet', 'Low Acid', 'Bright', 'Fresh', 'Umami'],
    pairings: ['Mozzarella di Bufala', 'Basil', 'Olive Oil', 'Pasta', 'Pizza'],
    pairingIds: ['mozzarella-bufala', 'basil', 'olive-oil', 'pasta', 'pizza'],
    nutrition: ['Low Calorie', 'Rich in Lycopene', 'Vegan', 'Gluten-Free'],
    producerIds: ['gustarosso'],
    recipeIds: ['pasta-alla-norma', 'tagliatelle-ragu'],
  },
  'mozzarella-di-bufala': {
    id: 'mozzarella-di-bufala', name: 'Mozzarella di Bufala DOP', region: 'campania', regionName: 'Campania',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'Porcelain-white mozzarella made from the milk of water buffalo raised in the plains of Campania. Eaten within hours of stretching, it is milky, elastic, and faintly tangy — nothing like its imitations.',
    flavors: ['Milky', 'Tangy', 'Fresh', 'Delicate', 'Elastic'],
    pairings: ['San Marzano', 'Basil', 'Olive Oil', 'Prosciutto', 'Pizza'],
    pairingIds: ['san-marzano', 'basil', 'olio-extra-vergine', 'prosciutto-di-parma', 'pizza'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Fresh Cheese', 'Vegetarian'],
    producerIds: ['caseificio-vannulo'],
    recipeIds: ['pizza-margherita'],
  },
  'prosciutto-di-parma': {
    id: 'prosciutto-di-parma', name: 'Prosciutto di Parma DOP', region: 'emilia_romagna', regionName: 'Emilia-Romagna',
    image: '/img/u/1625938144755-652e08e359b7-900.webp',
    description: 'Italy\'s most celebrated cured ham — only pork, sea salt, air, and a minimum of 12 months in the hills around Parma. Sweet, silky, and never smoked.',
    flavors: ['Sweet', 'Savory', 'Silky', 'Delicate', 'Nutty'],
    pairings: ['Parmigiano Reggiano', 'Melon', 'Figs', 'Balsamic', 'Grissini'],
    pairingIds: ['parmigiano-reggiano', 'melon', 'figs', 'aceto-balsamico', 'grissini'],
    nutrition: ['High Protein', 'No Additives', 'Air-Cured', 'Gluten-Free'],
    producerIds: ['prosciuttificio-san-nicola'],
    recipeIds: ['tagliatelle-ragu'],
  },
  'aceto-balsamico': {
    id: 'aceto-balsamico', name: 'Aceto Balsamico Tradizionale DOP', region: 'emilia_romagna', regionName: 'Emilia-Romagna',
    image: '/img/u/1474979266404-7eaacbcd87c5-900.webp',
    description: 'True balsamic from Modena is cooked grape must aged 12 to 25 years through a battery of wooden barrels, each adding its own perfume. Dense, sweet-sour, and used by the drop.',
    flavors: ['Sweet', 'Sour', 'Woody', 'Dense', 'Complex'],
    pairings: ['Parmigiano Reggiano', 'Strawberries', 'Risotto', 'Prosciutto', 'Vanilla Gelato'],
    pairingIds: ['parmigiano-reggiano', 'strawberries', 'risotto', 'prosciutto-di-parma', 'gelato'],
    nutrition: ['No Additives', 'Aged 12-25 Years', 'Vegan', 'Gluten-Free'],
    producerIds: ['acetaia-malpighi'],
    recipeIds: ['tagliatelle-ragu'],
  },
  'olio-extra-vergine': {
    id: 'olio-extra-vergine', name: 'Olio Extra Vergine Toscano IGP', region: 'toscana', regionName: 'Tuscany',
    image: '/img/u/1474979266404-7eaacbcd87c5-900.webp',
    description: 'Tuscan extra virgin olive oil is picked early and pressed cold — green, peppery, and assertively bitter in the best way. The throat-catching finish is a mark of fresh polyphenols, not a flaw.',
    flavors: ['Peppery', 'Grassy', 'Bitter', 'Green', 'Pungent'],
    pairings: ['Bread', 'Ribollita', 'Grilled Meat', 'White Beans', 'Pecorino'],
    pairingIds: ['bread', 'ribollita', 'bistecca', 'cannellini', 'pecorino-toscano'],
    nutrition: ['Rich in Polyphenols', 'Healthy Fats', 'Cold-Pressed', 'Vegan'],
    producerIds: ['frantoio-franci', 'olio-ardenghi'],
    recipeIds: [],
  },
  'pecorino-toscano': {
    id: 'pecorino-toscano', name: 'Pecorino Toscano DOP', region: 'toscana', regionName: 'Tuscany',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'The gentler cousin of Pecorino Romano — sheep\'s milk cheese from the Tuscan hills, sweet and grassy when young, deep and nutty when aged in the cellars of Pienza.',
    flavors: ['Sweet', 'Grassy', 'Nutty', 'Buttery', 'Mild'],
    pairings: ['Honey', 'Pears', 'Fava Beans', 'Chianti', 'Walnuts'],
    pairingIds: ['honey', 'pears', 'fava', 'chianti', 'walnuts'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Sheep\'s Milk', 'Vegetarian'],
    producerIds: ['caseificio-bianchi', 'podere-il-casale'],
    recipeIds: [],
  },
  'grana-padano': {
    id: 'grana-padano', name: 'Grana Padano DOP', region: 'lombardia', regionName: 'Lombardy',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'Born in Cistercian abbeys nearly a thousand years ago, Grana Padano is the Po Valley\'s great granular cheese — milder and creamier than Parmigiano, and Italy\'s most consumed DOP cheese.',
    flavors: ['Savory', 'Creamy', 'Nutty', 'Mild', 'Granular'],
    pairings: ['Risotto', 'Franciacorta', 'Pears', 'Bresaola', 'Honey'],
    pairingIds: ['risotto', 'franciacorta', 'pears', 'bresaola', 'honey'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Aged', 'Low Lactose'],
    producerIds: ['caseificio-lombardo'],
    recipeIds: ['risotto-milanese'],
  },
  'bresaola': {
    id: 'bresaola', name: 'Bresaola della Valtellina IGP', region: 'lombardia', regionName: 'Lombardy',
    image: '/img/products/bresaola-valtellina.webp',
    description: 'Air-dried salted beef from the alpine Valtellina valley — lean, deep ruby red, and delicately spiced. Sliced paper-thin with lemon, olive oil, and rocket, it is the lightest of Italy\'s great cured meats.',
    flavors: ['Lean', 'Delicate', 'Spiced', 'Savory', 'Clean'],
    pairings: ['Lemon', 'Rocket', 'Grana Padano', 'Olive Oil', 'Rye Bread'],
    pairingIds: ['lemon', 'rocket', 'grana-padano', 'olio-extra-vergine', 'rye'],
    nutrition: ['Very High Protein', 'Low Fat', 'Air-Cured', 'Gluten-Free'],
    producerIds: ['salumificio-valtellina'],
    recipeIds: [],
  },
  'pistacchio-di-bronte': {
    id: 'pistacchio-di-bronte', name: 'Pistacchio di Bronte DOP', region: 'sicilia', regionName: 'Sicily',
    image: '/img/products/pistacchio-bronte.webp',
    description: 'The "green gold" of Etna — pistachios grown on volcanic lava soil in Bronte, harvested only every second year. Intensely aromatic and emerald-green, they bear little resemblance to ordinary pistachios.',
    flavors: ['Intense', 'Sweet', 'Resinous', 'Buttery', 'Aromatic'],
    pairings: ['Mortadella', 'Gelato', 'Pasta', 'Ricotta', 'White Chocolate'],
    pairingIds: ['mortadella', 'gelato', 'pasta', 'ricotta', 'chocolate'],
    nutrition: ['Healthy Fats', 'High Protein', 'Volcanic Soil', 'Vegan'],
    producerIds: ['pistacchi-bronte'],
    recipeIds: [],
  },
  'nduja': {
    id: 'nduja', name: '\'Nduja di Spilinga', region: 'calabria', regionName: 'Calabria',
    image: '/img/products/nduja-toraldo.webp',
    description: 'Calabria\'s fiery spreadable salami from Spilinga — pork and enormous quantities of local chilli, fermented and smoked. It melts into anything warm, carrying slow-building heat and deep smokiness.',
    flavors: ['Fiery', 'Smoky', 'Rich', 'Spreadable', 'Fermented'],
    pairings: ['Burrata', 'Bruschetta', 'Pasta', 'Pizza', 'Honey'],
    pairingIds: ['burrata', 'bruschetta', 'pasta', 'pizza', 'honey'],
    nutrition: ['High Energy', 'Capsaicin-Rich', 'Fermented', 'Gluten-Free'],
    producerIds: ['salumeria-toraldo'],
    recipeIds: ['pasta-nduja'],
  },
  'limoncello': {
    id: 'limoncello', name: 'Limoncello di Sorrento', region: 'campania', regionName: 'Campania',
    image: '/img/lib/limoncello.webp',
    description: 'The Amalfi Coast\'s sunshine in a glass — liqueur made only from the zest of Sorrento IGP lemons steeped in alcohol. Served ice-cold after dinner, it should taste of fruit, not candy.',
    flavors: ['Citrus', 'Sweet', 'Zesty', 'Aromatic', 'Bright'],
    pairings: ['Desserts', 'Sgroppino', 'Fresh Fruit', 'Gelato', 'Pastiera'],
    pairingIds: ['desserts', 'sgroppino', 'fruit', 'gelato', 'pastiera'],
    nutrition: ['Digestivo', 'Natural Zest Only', 'No Colorants', 'Gluten-Free'],
    producerIds: ['antiche-distillerie-riunite'],
    recipeIds: [],
  },
  'burrata': {
    id: 'burrata', name: 'Burrata di Andria IGP', region: 'puglia', regionName: 'Apulia',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'A mozzarella shell hiding a heart of cream and shredded curd — invented in Andria in the 1920s to use every scrap of the day\'s stretching. Cut it open and it pours.',
    flavors: ['Creamy', 'Milky', 'Buttery', 'Fresh', 'Luxurious'],
    pairings: ['\'Nduja', 'Tomatoes', 'Olive Oil', 'Grilled Bread', 'Anchovies'],
    pairingIds: ['nduja', 'san-marzano', 'olio-extra-vergine', 'bread', 'acciughe'],
    nutrition: ['Rich in Calcium', 'Fresh Cheese', 'High Energy', 'Vegetarian'],
    producerIds: ['caseificio-montrone'],
    recipeIds: ['pasta-nduja'],
  },
  'bottarga': {
    id: 'bottarga', name: 'Bottarga di Muggine di Cabras', region: 'sardegna', regionName: 'Sardinia',
    image: '/img/lib/r-sardegna.webp',
    description: 'The "caviar of the Mediterranean" — salted, pressed, air-dried grey mullet roe from the Cabras lagoon. Shaved or grated over pasta, it delivers pure, concentrated umami of the sea.',
    flavors: ['Umami', 'Briny', 'Savory', 'Intense', 'Marine'],
    pairings: ['Spaghetti', 'Olive Oil', 'Lemon', 'Artichokes', 'Vermentino'],
    pairingIds: ['spaghetti', 'olio-extra-vergine', 'lemon', 'artichokes', 'vermentino'],
    nutrition: ['Very High Protein', 'Omega-3 Rich', 'Air-Dried', 'Gluten-Free'],
    producerIds: ['pescheria-giuliani'],
    recipeIds: [],
  },
  'fontina': {
    id: 'fontina', name: 'Fontina DOP', region: 'valle_daosta', regionName: "Valle d'Aosta",
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'Alpine cheese made from the raw milk of Valdostana cows grazing high mountain pastures, aged in humid rock caves. Sweet, earthy, and the best melting cheese in Italy — the soul of fonduta.',
    flavors: ['Earthy', 'Sweet', 'Nutty', 'Melting', 'Alpine'],
    pairings: ['Fonduta', 'Polenta', 'White Truffle', 'Rye Bread', 'Donnas'],
    pairingIds: ['fonduta', 'polenta', 'tartufo-bianco', 'rye', 'donnas'],
    nutrition: ['Raw Milk', 'Rich in Calcium', 'High Protein', 'Cave-Aged'],
    producerIds: ['cooperativa-produttori-fontina'],
    recipeIds: [],
  },
  'speck-alto-adige': {
    id: 'speck-alto-adige', name: 'Speck Alto Adige IGP', region: 'trentino_alto_adige', regionName: 'Trentino-Alto Adige',
    image: '/img/u/1625938144755-652e08e359b7-900.webp',
    description: 'South Tyrol\'s answer to prosciutto — lightly smoked over beech wood, then cured in crisp mountain air for at least 22 weeks. A Germanic technique married to Italian salt and herbs.',
    flavors: ['Smoky', 'Juniper', 'Savory', 'Herbal', 'Robust'],
    pairings: ['Rye Bread', 'Horseradish', 'Pickles', 'Canederli', 'Pinot Grigio'],
    pairingIds: ['rye', 'horseradish', 'pickles', 'canederli', 'pinot-grigio'],
    nutrition: ['High Protein', 'Smoked & Air-Cured', 'Mountain Product', 'Gluten-Free'],
    producerIds: ['speck-recla'],
    recipeIds: [],
  },
  'gianduiotto': {
    id: 'gianduiotto', name: 'Gianduiotto di Torino', region: 'piemonte', regionName: 'Piedmont',
    image: '/img/lib/chocolate.webp',
    description: 'Turin\'s ingot-shaped chocolate, born in 1865 when cocoa shortages pushed chocolatiers to blend in local hazelnut paste. The result — gianduja — became one of the world\'s great confections.',
    flavors: ['Hazelnut', 'Chocolate', 'Velvety', 'Sweet', 'Toasted'],
    pairings: ['Espresso', 'Barolo Chinato', 'Hazelnuts', 'Gelato', 'Vermouth'],
    pairingIds: ['espresso', 'barolo-chinato', 'hazelnuts', 'gelato', 'vermouth'],
    nutrition: ['Piedmont Hazelnuts', 'High Energy', 'Artisan-Made', 'Vegetarian'],
    producerIds: ['peyrano-cioccolato'],
    recipeIds: [],
  },
  'asiago': {
    id: 'asiago', name: 'Asiago DOP', region: 'veneto', regionName: 'Veneto',
    image: '/img/u/1486297678162-eb2a19b0a32d-900.webp',
    description: 'Cheese of the Veneto highlands, made on the Asiago plateau for a thousand years. Fresh Asiago is sweet and springy; aged "vecchio" turns sharp, crystalline, and intense.',
    flavors: ['Sweet', 'Tangy', 'Buttery', 'Sharp (aged)', 'Grassy'],
    pairings: ['Polenta', 'Speck', 'Pears', 'Prosecco', 'Honey'],
    pairingIds: ['polenta', 'speck-alto-adige', 'pears', 'prosecco', 'honey'],
    nutrition: ['High Protein', 'Rich in Calcium', 'Mountain Milk', 'Vegetarian'],
    producerIds: ['caseificio-pennar'],
    recipeIds: [],
  },
  'zafferano': {
    id: 'zafferano', name: "Zafferano dell'Aquila DOP", region: 'abruzzo', regionName: 'Abruzzo',
    image: '/img/lib/saffron-risotto.webp',
    description: 'Saffron from the Navelli plateau, hand-picked at dawn and toasted over embers — a tradition kept alive since the 13th century. Among the most potent saffron in the world, prized for risotto alla Milanese.',
    flavors: ['Floral', 'Honeyed', 'Earthy', 'Bitter-Sweet', 'Perfumed'],
    pairings: ['Risotto', 'Seafood', 'Potatoes', 'Chicken', 'Desserts'],
    pairingIds: ['risotto', 'seafood', 'potatoes', 'chicken', 'desserts'],
    nutrition: ['Antioxidant-Rich', 'Hand-Harvested', 'Vegan', 'Gluten-Free'],
    producerIds: ['zafferano-altopiano'],
    recipeIds: ['risotto-milanese'],
  },
};

export default ingredients;
