export const productsData = [
  {
    id: 'p1', name: 'Olio Extra Vergine Toscano DOP', producer: 'Frantoio Franci',
    region: 'Tuscany', regionId: 'toscana', category: 'Olive Oil',
    price: 18.90, weight: '500ml', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/f62bddbeb_generated_image.png',
    description: 'Cold-pressed from hand-picked Frantoio olives. Intense fruity aroma with peppery finish.',
    tags: ['DOP', 'Artisanal'],
  },
  {
    id: 'p2', name: 'Parmigiano Reggiano DOP 24 Mesi', producer: 'Caseificio Gennari',
    region: 'Emilia-Romagna', regionId: 'emilia_romagna', category: 'Cheese',
    price: 16.50, weight: '500g', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/5d70b18c7_generated_image.png',
    description: 'The king of Italian cheeses. Aged 24 months in Parma for a rich, crystalline texture.',
    tags: ['DOP'],
  },
  {
    id: 'p3', name: 'Aceto Balsamico Tradizionale DOP', producer: 'Acetaia Malpighi',
    region: 'Emilia-Romagna', regionId: 'emilia_romagna', category: 'Condiments',
    price: 24.90, weight: '100ml', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/c873ef73c_generated_image.png',
    description: 'Traditional balsamic vinegar aged 25 years in a succession of barrels. Complex and velvety.',
    tags: ['DOP', 'Artisanal'],
  },
  {
    id: 'p4', name: 'Prosciutto di Parma DOP', producer: 'Prosciuttificio San Nicola',
    region: 'Emilia-Romagna', regionId: 'emilia_romagna', category: 'Cured Meats',
    price: 18.00, weight: '500g', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/ae9828dae_generated_image.png',
    description: 'Delicately sweet Parma ham, air-cured for 18 months in the Langhirano hills.',
    tags: ['DOP'],
  },
  {
    id: 'p5', name: 'Brunello di Montalcino DOCG', producer: 'Cantina Rossi',
    region: 'Tuscany', regionId: 'toscana', category: 'Wine',
    price: 32.00, weight: '750ml', certifications: ['DOCG'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/64b0a269f_generated_image.png',
    description: "One of Italy's greatest reds. Sangiovese Grosso from Montalcino, aged minimum 5 years.",
    tags: ['DOCG'],
  },
  {
    id: 'p6', name: "Tartufo Bianco d'Alba", producer: 'Tartufi Morra',
    region: 'Piedmont', regionId: 'piemonte', category: 'Truffle',
    price: 45.00, weight: '30g', certifications: [],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/8fb7d1cd5_generated_image.png',
    description: 'The white gold of Piedmont. Hand-foraged Alba truffle with intensely aromatic profile.',
    tags: ['Seasonal', 'Artisanal'],
  },
  {
    id: 'p7', name: 'Mozzarella di Bufala DOP', producer: 'Caseificio Vannulo',
    region: 'Campania', regionId: 'campania', category: 'Cheese',
    price: 8.90, weight: '250g', certifications: ['DOP', 'Organic'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/ad4d252f2_generated_image.png',
    description: 'Organic buffalo mozzarella from Paestum, hand-stretched fresh daily. Silky and milky.',
    tags: ['DOP', 'Organic'],
  },
  {
    id: 'p8', name: 'Prosecco Superiore DOCG', producer: 'Cantina Bisol',
    region: 'Veneto', regionId: 'veneto', category: 'Wine',
    price: 14.90, weight: '750ml', certifications: ['DOCG'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/e0d9fa9af_generated_image.png',
    description: 'Elegant sparkling wine from the original Valdobbiadene hills. Fine bubbles, floral notes.',
    tags: ['DOCG'],
  },
  {
    id: 'p9', name: 'Nduja di Spilinga IGP', producer: 'Salumeria Toraldo',
    region: 'Calabria', regionId: 'calabria', category: 'Cured Meats',
    price: 9.90, weight: '200g', certifications: ['IGP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/99f8d5343_generated_image.png',
    description: 'Fiery spreadable salami from Spilinga. Made with local Calabrian chillies and pork.',
    tags: ['IGP', 'Artisanal'],
  },
  {
    id: 'p10', name: 'Pesto Genovese DOP', producer: 'Pesto Rossi',
    region: 'Liguria', regionId: 'liguria', category: 'Condiments',
    price: 7.50, weight: '180g', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/a4ec9e8a3_generated_image.png',
    description: 'Authentic Genovese pesto made with DOP Ligurian basil, pine nuts and aged Parmigiano.',
    tags: ['DOP', 'Vegan'],
  },
  {
    id: 'p11', name: 'Barolo DOCG Riserva', producer: 'Giacomo Conterno',
    region: 'Piedmont', regionId: 'piemonte', category: 'Wine',
    price: 38.00, weight: '750ml', certifications: ['DOCG'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/9c22dd333_generated_image.png',
    description: "The king of Italian wines. Nebbiolo from Serralunga d'Alba, aged 7 years minimum.",
    tags: ['DOCG'],
  },
  {
    id: 'p12', name: 'Pistacchio di Bronte DOP', producer: 'Pistacchi Bronte',
    region: 'Sicily', regionId: 'sicilia', category: 'Nuts',
    price: 12.90, weight: '250g', certifications: ['DOP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/05f7fa7b1_generated_image.png',
    description: "The world's finest pistachios grown on Mt. Etna volcanic soil. Intensely flavourful.",
    tags: ['DOP', 'Vegan', 'Gluten-Free'],
  },
  {
    id: 'p13', name: 'Speck Alto Adige IGP', producer: 'Speck Recla',
    region: 'Trentino-Alto Adige', regionId: 'trentino_alto_adige', category: 'Cured Meats',
    price: 16.50, weight: '400g', certifications: ['IGP'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/8d604c924_generated_image.png',
    description: 'Mountain-air cured and cold-smoked in South Tyrol. Uniquely balanced between prosciutto and speck.',
    tags: ['IGP', 'Artisanal'],
  },
  {
    id: 'p14', name: 'Miele di Acacia Bio', producer: 'Miele dei Colli',
    region: 'Lazio', regionId: 'lazio', category: 'Honey',
    price: 9.90, weight: '500g', certifications: ['Organic'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/0321c8636_generated_image.png',
    description: 'Delicate organic acacia honey from the Alban Hills. Light amber, floral and sweet.',
    tags: ['Organic', 'Vegan', 'Gluten-Free'],
  },
  {
    id: 'p15', name: 'Cannonau di Sardegna DOC', producer: 'Cantina Argiolas',
    region: 'Sardinia', regionId: 'sardegna', category: 'Wine',
    price: 13.90, weight: '750ml', certifications: ['DOC'],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/cebc35c7a_generated_image.png',
    description: 'The iconic Sardinian red. Full-bodied with notes of ripe cherry and Mediterranean herbs.',
    tags: ['DOC'],
  },
  {
    id: 'p16', name: 'Pasta Orecchiette Artigianale', producer: 'Pastificio Cavalieri',
    region: 'Apulia', regionId: 'puglia', category: 'Pasta',
    price: 5.90, weight: '500g', certifications: [],
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/a6ea6a58c_generated_image.png',
    description: 'Traditional Pugliese ear-shaped pasta, bronze-die extruded and slow dried for 48 hours.',
    tags: ['Artisanal', 'Vegan'],
  },
];

export const categories = [
  { name: 'Olive Oil', emoji: '🫒', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/edb6dea94_generated_image.png' },
  { name: 'Wine', emoji: '🍷', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/f4352a214_generated_image.png' },
  { name: 'Cheese', emoji: '🧀', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/61a8be35b_generated_image.png' },
  { name: 'Pasta', emoji: '🍝', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/3e403693c_generated_image.png' },
  { name: 'Coffee', emoji: '☕', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/916e7d581_generated_image.png' },
  { name: 'Cured Meats', emoji: '🥩', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/53fe23167_generated_image.png' },
  { name: 'Honey', emoji: '🍯', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/0e9b3e850_generated_image.png' },
  { name: 'Truffle', emoji: '🍄', image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/8520f89a5_generated_image.png' },
];