// Recipe dataset for Bottega Delivery.
// Each recipe id is referenced elsewhere (gastronomySpots `to:`, Ingredient.recipeIds,
// creatorsData.recipes, GastronomyNetwork). Keep ids stable.
// ingredient.producerId, when present, is a slug that resolves to a real producer
// detail page (matched by name-slug against regionData producers).

export const recipeCategories = ['All', 'Pasta', 'Pizza', 'Rice'];

export const recipesData = [
  {
    id: 'cacio-e-pepe',
    name: 'Cacio e Pepe',
    regionName: 'Lazio',
    category: 'Pasta',
    difficulty: 'Medium',
    cookTime: '20 min',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900&q=80',
    description: 'Three ingredients, zero margin for error: Pecorino Romano, black pepper, and pasta water emulsified into the silkiest sauce in Roman cooking.',
    creator: { id: 'chef-antonio', name: 'Chef Antonio Rossi' },
    culturalStory: 'Born among the shepherds of the Roman countryside, cacio e pepe was the meal you could carry: dried pasta, aged pecorino, and pepper that kept for the long transhumance. Its genius is restraint. There is nowhere to hide, which is exactly why every Roman trattoria is judged by it.',
    ingredients: [
      { name: 'Tonnarelli (or spaghetti)', amount: '320 g', producerId: 'pastificio-felicetti' },
      { name: 'Pecorino Romano DOP, finely grated', amount: '180 g', producerId: 'caseificio-bianchi' },
      { name: 'Black peppercorns, freshly cracked', amount: '1 tbsp' },
      { name: 'Sea salt', amount: 'to taste' },
    ],
    steps: [
      'Toast the cracked pepper in a dry pan for 30 seconds until fragrant, then add a ladle of starchy pasta water and let it steep.',
      'Cook the pasta in lightly salted water until very al dente, reserving a mug of the cooking water.',
      'In a bowl, whisk the pecorino with a little warm (not hot) pasta water into a smooth paste.',
      'Off the heat, toss the pasta with the pepper, then fold in the pecorino cream, adding water bit by bit until it coats every strand.',
      'Serve immediately, finishing with more pecorino and pepper.',
    ],
    relatedRecipes: ['carbonara', 'tagliatelle-ragu'],
  },
  {
    id: 'carbonara',
    name: 'Spaghetti alla Carbonara',
    regionName: 'Lazio',
    category: 'Pasta',
    difficulty: 'Medium',
    cookTime: '25 min',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=900&q=80',
    description: 'Guanciale, egg yolks, Pecorino Romano and pepper. No cream, no garlic, no shortcuts - the discipline is the dish.',
    creator: { id: 'chef-antonio', name: 'Chef Antonio Rossi' },
    culturalStory: 'Carbonara is a postwar Roman invention, its name tangled in legends of charcoal workers and American GI rations of eggs and bacon. What is not debatable is the technique: the heat of the pasta, not a flame, must cook the yolks into a glossy sauce. Scramble it and you have failed; nail it and it is sublime.',
    ingredients: [
      { name: 'Spaghetti', amount: '320 g', producerId: 'pastificio-felicetti' },
      { name: 'Guanciale, cut into lardons', amount: '150 g', producerId: 'salumificio-falorni' },
      { name: 'Egg yolks', amount: '4' },
      { name: 'Pecorino Romano DOP, grated', amount: '80 g', producerId: 'caseificio-bianchi' },
      { name: 'Black pepper', amount: 'to taste' },
    ],
    steps: [
      'Render the guanciale in a cold pan over medium heat until the fat is translucent and the edges crisp. Keep the rendered fat.',
      'Whisk the yolks with the pecorino and a generous amount of pepper into a paste.',
      'Cook the spaghetti until al dente, reserving pasta water.',
      'Off the heat, combine the pasta with the guanciale and its fat, then add the egg-pecorino mix, loosening with pasta water until creamy.',
      'Plate at once with extra pecorino and pepper. The residual heat sets the sauce - never return it to the flame.',
    ],
    relatedRecipes: ['cacio-e-pepe', 'tagliatelle-ragu'],
  },
  {
    id: 'pasta-alla-norma',
    name: 'Pasta alla Norma',
    regionName: 'Sicilia',
    category: 'Pasta',
    difficulty: 'Easy',
    cookTime: '40 min',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=900&q=80',
    description: 'Catania on a plate: fried aubergine, sweet tomato, basil and a snowfall of salted ricotta.',
    creator: { id: 'chef-sofia', name: 'Chef Sofia Rizzo' },
    culturalStory: 'Said to be named after Bellini\'s opera Norma - a Catanese masterpiece for a Catanese masterpiece - this dish is Sicily\'s love letter to the aubergine. The volcanic soil of Etna gives the vegetables and tomatoes an intensity you taste in every forkful.',
    ingredients: [
      { name: 'Rigatoni or maccheroni', amount: '320 g', producerId: 'pastificio-felicetti' },
      { name: 'Aubergines, cubed', amount: '2 large' },
      { name: 'San Marzano tomatoes, peeled', amount: '400 g' },
      { name: 'Ricotta salata, grated', amount: '100 g' },
      { name: 'Fresh basil', amount: '1 bunch' },
      { name: 'Extra virgin olive oil', amount: 'for frying' },
    ],
    steps: [
      'Salt the aubergine cubes and drain for 20 minutes, then fry in hot olive oil until golden. Drain on paper.',
      'Simmer the tomatoes with a glug of oil and a few basil leaves until thick and sweet, about 15 minutes.',
      'Cook the pasta al dente and toss with the tomato sauce and most of the aubergine.',
      'Finish with torn basil and a heavy grating of ricotta salata, reserving some aubergine and cheese for the top.',
    ],
    relatedRecipes: ['pizza-margherita', 'pasta-nduja'],
  },
  {
    id: 'pasta-nduja',
    name: "Pasta alla 'Nduja",
    regionName: 'Calabria',
    category: 'Pasta',
    difficulty: 'Easy',
    cookTime: '25 min',
    image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=900&q=80',
    description: "Calabria's spreadable fire - 'nduja - melted into tomato until the whole pan glows red.",
    creator: { id: 'chef-sofia', name: 'Chef Sofia Rizzo' },
    culturalStory: "'Nduja is the soul of Spilinga, a soft, spicy salume of pork and Calabrian chillies that melts rather than slices. Stirred into a quick tomato sauce it dissolves into pure heat and depth - peasant ingenuity turned into one of Italy's most addictive plates of pasta.",
    ingredients: [
      { name: 'Mezze maniche or penne', amount: '320 g', producerId: 'pastificio-felicetti' },
      { name: "'Nduja di Spilinga", amount: '80 g' },
      { name: 'San Marzano tomatoes, crushed', amount: '400 g' },
      { name: 'Garlic clove', amount: '1' },
      { name: 'Pecorino, grated', amount: 'to serve', producerId: 'caseificio-bianchi' },
    ],
    steps: [
      "Warm the garlic in olive oil, then melt the 'nduja until it breaks down into the oil.",
      'Add the crushed tomatoes and simmer 10-12 minutes until glossy and deep red.',
      'Cook the pasta al dente and toss in the sauce with a splash of pasta water.',
      'Serve with grated pecorino - the dairy tempers the heat just enough.',
    ],
    relatedRecipes: ['pasta-alla-norma', 'pizza-margherita'],
  },
  {
    id: 'pizza-margherita',
    name: 'Pizza Margherita',
    regionName: 'Campania',
    category: 'Pizza',
    difficulty: 'Hard',
    cookTime: '90 min + proof',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=900&q=80',
    description: 'The Neapolitan original: San Marzano tomato, fior di latte or mozzarella di bufala, basil - the colours of the Italian flag.',
    creator: { id: 'chef-antonio', name: 'Chef Antonio Rossi' },
    culturalStory: 'In 1889 Naples pizzaiolo Raffaele Esposito is said to have built a pizza in the colours of the new nation\'s flag for Queen Margherita: red tomato, white mozzarella, green basil. Whether or not the tale is exact, the Margherita became the benchmark - protected today as a Specialita Tradizionale Garantita with rules on dough, heat and time.',
    ingredients: [
      { name: 'Tipo 00 flour', amount: '500 g' },
      { name: 'Water', amount: '325 ml' },
      { name: 'Fresh yeast', amount: '2 g' },
      { name: 'Fine salt', amount: '10 g' },
      { name: 'San Marzano tomatoes, hand-crushed', amount: '300 g' },
      { name: 'Mozzarella di bufala', amount: '250 g' },
      { name: 'Fresh basil and olive oil', amount: 'to finish' },
    ],
    steps: [
      'Dissolve the yeast in the water, add flour, then salt, and knead to a smooth elastic dough. Bulk-ferment 2 hours, then ball and proof 6-8 hours.',
      'Hand-stretch each ball to a 30 cm disc, leaving a puffy rim - never use a rolling pin.',
      'Top with crushed San Marzano (just salt, no cooking), torn mozzarella, and a thread of oil.',
      'Bake in the hottest oven you have (ideally 450-480 C for 60-90 seconds; in a home oven, max heat on a preheated stone).',
      'Finish with fresh basil out of the oven.',
    ],
    relatedRecipes: ['pasta-alla-norma', 'cacio-e-pepe'],
  },
  {
    id: 'risotto-milanese',
    name: 'Risotto alla Milanese',
    regionName: 'Lombardia',
    category: 'Rice',
    difficulty: 'Medium',
    cookTime: '35 min',
    image: 'https://images.unsplash.com/photo-1633436375153-d7045cb93e38?w=900&q=80',
    description: 'Saffron-gold risotto mantecato with butter and Grana Padano - Milan\'s most elegant plate.',
    creator: { id: 'chef-lucia', name: 'Chef Lucia Ferretti' },
    culturalStory: 'Legend gives it to a glassmaker\'s apprentice who tinted a wedding risotto with the saffron he used on stained glass for the Duomo. Real or not, saffron made this rice a symbol of Milanese luxury, traditionally served alongside ossobuco. The mantecatura - beating in cold butter and cheese off the heat - is what makes it shimmer.',
    ingredients: [
      { name: 'Carnaroli rice', amount: '320 g' },
      { name: 'Saffron threads', amount: '1 pinch' },
      { name: 'Beef or chicken stock, hot', amount: '1.2 L' },
      { name: 'Grana Padano DOP, grated', amount: '80 g', producerId: 'caseificio-lombardo' },
      { name: 'Butter', amount: '60 g' },
      { name: 'Shallot, fine diced', amount: '1' },
    ],
    steps: [
      'Sweat the shallot in a little butter, add the rice and toast until the grains are translucent at the edges.',
      'Add stock a ladle at a time, stirring, keeping the rice at a gentle simmer.',
      'Halfway through, bloom the saffron in a little hot stock and stir it in.',
      'When the rice is al dente and creamy (about 18 minutes), pull off the heat.',
      'Mantecare: beat in cold butter and Grana Padano vigorously until glossy. Rest 1 minute and serve all\'onda - loose and wavy.',
    ],
    relatedRecipes: ['tagliatelle-ragu', 'tajarin-tartufo'],
  },
  {
    id: 'tagliatelle-ragu',
    name: 'Tagliatelle al Ragu Bolognese',
    regionName: 'Emilia-Romagna',
    category: 'Pasta',
    difficulty: 'Medium',
    cookTime: '3 hr',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=900&q=80',
    description: 'The real Bolognese: a slow, milk-enriched meat ragu on fresh egg tagliatelle - never spaghetti.',
    creator: { id: 'chef-lucia', name: 'Chef Lucia Ferretti' },
    culturalStory: 'The Bolognese guard their ragu like a state secret - a recipe lodged with the Chamber of Commerce in 1982 specifies the cut of meat and the egg tagliatelle it belongs to. Patience is the only real ingredient: hours of the gentlest simmer, a little milk to soften, and wide ribbons of pasta that catch the sauce.',
    ingredients: [
      { name: 'Fresh egg tagliatelle', amount: '400 g', producerId: 'pastificio-felicetti' },
      { name: 'Coarse-ground beef and pork', amount: '500 g' },
      { name: 'Pancetta, minced', amount: '80 g', producerId: 'salumificio-falorni' },
      { name: 'Soffritto (onion, carrot, celery)', amount: '1 cup' },
      { name: 'Whole milk', amount: '200 ml' },
      { name: 'White wine and passata', amount: '150 ml + 400 g' },
      { name: 'Parmigiano Reggiano', amount: 'to serve' },
    ],
    steps: [
      'Soften the soffritto with the pancetta, then raise the heat and brown the meat well.',
      'Deglaze with white wine and let it evaporate, then add the passata.',
      'Pour in the milk and bring to the barest simmer; cook uncovered 2.5-3 hours, topping up with stock or water as needed.',
      'Cook the tagliatelle in salted water, drain, and toss with the ragu and a little starchy water.',
      'Finish with Parmigiano Reggiano.',
    ],
    relatedRecipes: ['risotto-milanese', 'cacio-e-pepe'],
  },
  {
    id: 'tajarin-tartufo',
    name: 'Tajarin al Tartufo',
    regionName: 'Piemonte',
    category: 'Pasta',
    difficulty: 'Hard',
    cookTime: '1 hr',
    image: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=900&q=80',
    description: 'Hand-cut 40-yolk Piedmontese pasta, butter, and shavings of white truffle from Alba.',
    creator: { id: 'chef-luca', name: 'Chef Luca Carnevale' },
    culturalStory: 'Tajarin is the Langhe\'s show of richness - a pasta worked with an extravagance of egg yolks, cut to threads by hand. In autumn it becomes the carrier for the most precious ingredient in Italy: the white truffle of Alba, shaved tableside over nothing more than melted butter so the perfume can speak.',
    ingredients: [
      { name: 'Tajarin (egg-yolk pasta)', amount: '320 g' },
      { name: 'Butter', amount: '80 g' },
      { name: 'White truffle from Alba', amount: 'to shave' },
      { name: 'Grana Padano, grated', amount: '40 g', producerId: 'caseificio-lombardo' },
      { name: 'Sage leaves', amount: '4' },
    ],
    steps: [
      'Gently melt the butter with the sage until it just foams - do not brown it; the truffle wants a clean canvas.',
      'Cook the tajarin for 60-90 seconds in salted water; it is delicate.',
      'Toss the pasta in the sage butter with a spoon of pasta water and the cheese.',
      'Plate and shave white truffle generously over the top at the table.',
    ],
    relatedRecipes: ['risotto-milanese', 'tagliatelle-ragu'],
  },
  {
    id: 'trofie-al-pesto',
    name: 'Trofie al Pesto Genovese',
    regionName: 'Liguria',
    category: 'Pasta',
    difficulty: 'Easy',
    cookTime: '30 min',
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=900&q=80',
    description: 'Twisted Ligurian trofie with basil pesto pounded in a mortar, plus the traditional potato and green beans.',
    creator: { id: 'chef-marco', name: 'Chef Marco Bianchi' },
    culturalStory: 'Genoa\'s pesto is a ritual as much as a sauce: Genovese DOP basil, pine nuts, garlic, two cheeses and Ligurian olive oil ground in a marble mortar with a wooden pestle - the friction, not a blade, keeps it sweet and green. Tradition tosses it with trofie, plus slices of potato and green beans cooked in the same pot.',
    ingredients: [
      { name: 'Trofie', amount: '350 g' },
      { name: 'Genovese basil leaves', amount: '60 g' },
      { name: 'Pine nuts', amount: '30 g' },
      { name: 'Garlic', amount: '1 clove' },
      { name: 'Parmigiano + Pecorino, grated', amount: '50 g', producerId: 'caseificio-bianchi' },
      { name: 'Ligurian extra virgin olive oil', amount: '120 ml', producerId: 'olio-ardenghi' },
      { name: 'Small potato + green beans', amount: '1 + handful' },
    ],
    steps: [
      'Pound the garlic and pine nuts to a paste in a mortar, add the basil with a few grains of coarse salt and grind in circles.',
      'Work in the cheeses, then stream in the olive oil until you have a loose, bright green sauce.',
      'Boil the potato slices, add the green beans, then the trofie, cooking everything together until the pasta is al dente.',
      'Loosen the pesto with a spoon of cooking water and toss off the heat - never cook the pesto.',
    ],
    relatedRecipes: ['cacio-e-pepe', 'pasta-alla-norma'],
  },
];

export default recipesData;
