export const storiesData = [
  {
    id: 's1',
    title: 'The Last Rice Farmers of Monferrato',
    category: 'Producer Story',
    region: 'Piedmont',
    excerpt: 'Matteo Costanzo tends the same paddy fields his grandfather worked, producing Carnaroli rice for the finest risotto kitchens in Europe. We spend a day in the Po Valley understanding why great risotto begins long before the kitchen.',
    readTime: '6 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/9b8e7db72_generated_image.png',
    tall: true,
  },
  {
    id: 's2',
    title: 'Why Modena Balsamic is Worth More Than Gold',
    category: 'Food History',
    region: 'Emilia-Romagna',
    excerpt: "Traditional balsamic vinegar from Modena can cost €300 for 100ml. It's not marketing — it's 25 years of patient aging in seven successive barrels. Here's the full story.",
    readTime: '8 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/70c592df2_generated_image.png',
    tall: false,
  },
  {
    id: 's3',
    title: 'Nduja: The Spreadable Fire of Calabria',
    category: 'Regional Culture',
    region: 'Calabria',
    excerpt: 'Born in the hills of Spilinga, nduja is Calabria concentrated — fiery, fatty, deeply savoury. A working-class food that became a global obsession. Meet the family that still makes it the original way.',
    readTime: '5 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/8490b2c9a_generated_image.png',
    tall: false,
  },
  {
    id: 's4',
    title: 'A Day at a Buffalo Farm in Paestum',
    category: 'Producer Story',
    region: 'Campania',
    excerpt: "Caseificio Vannulo milks its organic buffalo at 4am and has mozzarella on the table by 8am. There is no fresher mozzarella di bufala DOP on earth. We spent a full day to understand why.",
    readTime: '7 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/ec6ef1dcd_generated_image.png',
    tall: true,
  },
  {
    id: 's5',
    title: 'The Art of Aging Parmigiano Reggiano',
    category: 'Traditional Recipe',
    region: 'Emilia-Romagna',
    excerpt: 'Each wheel of Parmigiano Reggiano weighs 40kg and contains 550 litres of milk. It takes a minimum of 12 months of aging before a needle test determines its fate. The science and art behind the king of cheeses.',
    readTime: '9 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/26d4078b4_generated_image.png',
    tall: false,
  },
  {
    id: 's6',
    title: 'Truffle Season in Norcia',
    category: 'Regional Culture',
    region: 'Umbria',
    excerpt: "Between October and December, the forests around Norcia belong to the tartufai. Three generations of the Bianconi family wake before dawn to hunt the black diamonds of the Umbrian woods.",
    readTime: '6 min read',
    image: 'https://media.base44.com/images/public/69b28610d2d035157c27d27a/dd1e8092d_generated_image.png',
    tall: false,
  },
];

export const storyCategories = ['All', 'Producer Story', 'Regional Culture', 'Traditional Recipe', 'Food History'];